from tkinter import *
root=Tk()
root.title('login')
root.geometry('400x400')
frame=Frame(master=root,height=200,width=360,bg="green")
label1=Label(frame,text='full name',bg="white",fg='yellow',width=12)
label2=Label(frame,text='email id',bg="white",fg='yellow',width=12)
label3=Label(frame,text='password',bg="white",fg='yellow',width=12)
name_entry=Entry(frame)
email_entry=Entry(frame)
pass_entry=Entry(frame,show="*")

frame.place(x=20,y=0)
label1.place(x=20,y=20)
name_entry.place(x=150,y=20)
label2.place(x=20,y=80)
email_entry.place(x=150,y=80)
label3.place(x=20,y=140)
pass_entry.place(x=150,y=140)
root.mainloop()